CREATE TABLE ISSUESLISTS
(
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100)
);

CREATE TABLE ISSUESS
(
    ID SERIAL PRIMARY KEY,
    ISSUESLIST_ID BIGINT UNSIGNED NOT NULL,
    SUMMARY VARCHAR(100),
    DESCRIPTION VARCHAR(1024),
    USER_ID_ASSIGNEDTO BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY (ISSUESLIST_ID) REFERENCES ISSUESLISTS(ID),
    FOREIGN KEY (USER_ID_ASSIGNEDTO) REFERENCES USERS(ID)
);

COMMIT;

INSERT INTO ISSUESLISTS (NAME) VALUES ('ToDo');
INSERT INTO ISSUESLISTS (NAME) VALUES ('In progress');
INSERT INTO ISSUESLISTS (NAME) VALUES ('Done');

COMMIT;

INSERT INTO ISSUESS(ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (1, 'Documents', 'Submission of all required documents', 1);

INSERT INTO ISSUESS(ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (1, 'Projects', 'House Project', 1);

INSERT INTO ISSUESS(ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (1, 'Building', 'Building a house', 2);

INSERT INTO ISSUESS(ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (1, 'Service', 'Installation of windows, doors, blinds', 3);

INSERT INTO ISSUESS(ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (1,  'Installation', 'installation of water, sewage, electricity', 4);

INSERT INTO ISSUESS(ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (1,  'Interior finishing', 'insulation, plastering, painting', 5);



INSERT INTO ISSUESS(ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (2, 'Building', 'Roof construction', 2);

INSERT INTO ISSUESS(ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (2, 'Installation', 'Installation of water', 4);

INSERT INTO ISSUESS(ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (2, 'Installation', 'Installation of electricity', 4);

INSERT INTO ISSUESS(ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (2, 'Installation', 'Installation of sewage', 4);

INSERT INTO ISSUESS(ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (2, 'Service', 'Installation of windows', 3);

INSERT INTO ISSUESS(ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (2, 'Service', 'Installation of blinds', 3);

INSERT INTO ISSUESS(ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (2, 'Service', 'Installation of doors', 3);

INSERT INTO ISSUESS(ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (2, 'Interior finishing', 'Insulation', 5);

INSERT INTO ISSUESS(ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (2, 'Interior finishing','Plastering', 5);

INSERT INTO ISSUESS(ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (2, 'Interior finishing','Painting', 5);



INSERT INTO ISSUESS(ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (3, 'Projects', 'Project House', 1);

INSERT INTO ISSUESS(ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (3, 'Documents', 'Permits to build', 1);

INSERT INTO ISSUESS(ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (3, 'Documents', 'Entry in the Land Register', 1);

INSERT INTO ISSUESS(ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (3, 'Building', 'Foundations and walls put up', 2);

INSERT INTO ISSUESS(ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (3, 'Projects', 'Land demarcation', 1);

COMMIT;
