SELECT I.SUMMARY, IL.NAME
FROM ISSUESLISTS IL
JOIN ISSUESS I ON IL.ID = I.ISSUESLIST_ID;

SELECT DISTINCT I.SUMMARY, U.FIRSTNAME, U.LASTNAME
FROM ISSUESS I
JOIN USERS U on I.USER_ID_ASSIGNEDTO = U.ID;

SELECT DISTINCT U.FIRSTNAME, U.LASTNAME, COUNT(*) AS NUMBER_TASKS
FROM USERS U JOIN ISSUESS I ON U.ID = I.USER_ID_ASSIGNEDTO
GROUP BY U.FIRSTNAME, U.LASTNAME
HAVING COUNT(*) >1;